[build]
  command = "npm run build"  # Run Vite build
  functions = "functions"    # Match your functions directory
  publish = "dist"           # Vite's output directory

[dev]
  targetPort = 8080          # Match Vite's port from netlify dev output
  port = 8888                # Netlify Dev's local server port

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
