[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[dev]
  targetPort = 8080
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
