[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  targetPort = 3000
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false
[build.processing.js]
  bundle = false
  minify = false

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
